version: '3'
services:
    app:
        container_name: second-number-app
        hostname: ${HOSTNAME}
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: unless-stopped
        tty: true
        env_file: .env
        working_dir: /var/www/html
        networks:
            - second-number-network
        volumes:
            - ./app:/var/www/html
    webserver:
        container_name: second-number-webserver
        image: nginx:alpine3.20-slim
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        networks:
            - second-number-network
        volumes:
            - ./app:/var/www/html
            - ./docker/nginx/conf.d.dev:/etc/nginx/conf.d
    db:
        container_name: second-number-db
        image: mysql:8.4
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        networks:
            - second-number-network
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
networks:
    second-number-network:
        driver: bridge
